[package]
name = "mono_sys"
version = "0.1.0"
authors = ["Ketan C.S. Reynolds <ketan.cs.reynolds@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.54"

[dependencies]
